import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
        style={{
          backgroundColor: "#000",
          color: "#fff",
          minHeight: "100vh",
          margin: 0,
        }}
      >
        {/* ✅ “가장 원초적이고 확실한 방법”: CSS가 하나도 로드되지 않아도 무조건 다크 바탕 강제 */}
        <style>{`
          html, body {
            background: #000 !important;
            color: #fff !important;
            height: 100%;
            margin: 0;
          }
          a { color: inherit; }
          * { box-sizing: border-box; }
        `}</style>
        {children}
      </body>
    </html>
  );
}
